### ISSUE TITLE
Configure Ethnio intercept on both data portal production sites

### ISSUE THREAD

**Issue by yesenia-gtz** [CA-Data/Open-Data-Portal#113]
ISSUE LEAD: @hamiltonryan 

In order to measure User Satisfaction we would like to understand baseline data on both data.ca.gov and compare that data to lab.data.ca.gov.

Related tasks:
- [x] Contact ODI to get Ethnio account access
- [x] Draft questions to measure user satisfaction
- [x] Review questions with UX Lead and Product Manager for feedback
- [x] Finalize questions per feedback
- [ ] Work with Sam to facilitate access to edit intercept on data.ca.gov
- [ ] Add intercept to lab.data.ca.gov
- [ ] Share access to incoming data with Product Manager

**Comment by hamiltonryan** [comment]
I have reached out to ODI, and am working to see what we can do on their side. I also reached out to Steven, about getting our own account, since that has been in the works for a while. He sent the request up to Art and Blaine.

**Comment by yesenia-gtz** [comment]
@KarunaTamatam FYI
