### ISSUE TITLE
API findability A/B user satisfaction testing

### ISSUE THREAD

**Issue by yesenia-gtz** [CA-Data/Open-Data-Portal#115]
ISSUE LEAD: @hamiltonryan 

A/B user satisfaction testing to measure API findability on data.ca.gov and lab.data.ca.gov

Tasks:
- [x] Draft 3-5 questions related to user satisfaction
- [x] Review questions with Product Manager and UX Lead
- [x] Finalize questions
- [x] Setup A/B test on usertesting.com
- [ ] Document insights in Coda
- [ ] Share insights with team

**Comment by hamiltonryan** [comment]
The user test for this have been launched.

**Comment by hamiltonryan** [comment]
This is part of the usability test being shared out this afternoon. I'll close this one as soon as that is finalized.
