### ISSUE TITLE
A/B testing Search Filter organization

### ISSUE THREAD

**Issue by yesenia-gtz** [CA-Data/Open-Data-Portal#118]
A/B testing Search Filter organization via usertesting.com:
- Numerically
- A-Z

**Comment by hamiltonryan** [comment]
This is similar to the other A/B test currently being integrated into the Surveys for a first pass, and depending how that goes there are simple A/B test prepared, as well as more creative option we could explore.

**Comment by hamiltonryan** [comment]
This is part of the usability test being complete in our share out this afternoon. I'll go ahead and close it now,
