### ISSUE TITLE
A/B testing Topics homepage and Landing page

### ISSUE THREAD

**Issue by yesenia-gtz** [CA-Data/Open-Data-Portal#119]
A/B testing Topics homepage and Landing page via usertesting.com:

Numerically
A-Z

**Comment by hamiltonryan** [comment]
Currently this is being integrated into the Surveys for a first pass, and depending how that goes there are simple A/B test prepared, as well as more creative option we could explore.

**Comment by hamiltonryan** [comment]
This is part of our Usability test being shared out this afternoon. I'll close this now to clean up the board.
