### ISSUE TITLE
UAT fix: ArcGIS and data displays

### ISSUE THREAD

**Issue by extinah** [CA-Data/Open-Data-Portal#121]
Some of the data displays (preview, download, api) are wrong.

API:
Currently ArcGIS displays API - and it shouldn't. 
Only CSV files should display an API link.
Only display API option when datastore flag = true. Talk to Jason if you need more info.

ArcGIS Geoservice:
No download link.
Change "Preview" to "View" 

ArcGIS Hub Dataset:
No download link
Change Preview to View map

**Comment by Greg-Watanabe** [comment]
This is complete
https://sandbox.data.ca.gov/dataset?name=nifc-2022-wildfire-perimeters1
@sharon-rabang

**Comment by sharon-rabang** [comment]
@Greg-Watanabe Looks good, thanks! Please add the changes to https://lab.data.ca.gov/ and let me know when it's done.

**Comment by sharon-rabang** [comment]
@Greg-Watanabe Completed review of https://lab.data.ca.gov/dataset/calfresh-healthy-living-gis. Closing this issue, thanks!
