### ISSUE TITLE
UAT Fix: Organization website URL

### ISSUE THREAD

**Issue by extinah** [CA-Data/Open-Data-Portal#122]
Greg is already working on this.

Website was added in by Sam in the description.

Trying to put website on separate line for now (make it linked if possible

Current
![1775e28a-9f48-4722-8db2-cbc499074aa8](https://user-images.githubusercontent.com/33840424/180331269-dd713bac-75e2-4f58-b55a-50c8a13bbefd.jpg)

Figma prototype
![31ba1108-4cd3-460e-bcb9-7920c0188aa8](https://user-images.githubusercontent.com/33840424/180331485-cf6b8df4-f0af-475c-8a3c-1c094e7ff518.jpg)

**Comment by Greg-Watanabe** [comment]
This is done
https://sandbox.data.ca.gov/organization/datasets?q=&publisher=cal-fire

**Comment by Greg-Watanabe** [comment]
This is done
https://sandbox.data.ca.gov/organization/datasets?q=&publisher=cal-fire
@sharon-rabang

**Comment by sharon-rabang** [comment]
@Greg-Watanabe Looks good, thanks! Please add the changes to https://lab.data.ca.gov/ and let me know when it's done.

**Comment by sharon-rabang** [comment]
@Greg-Watanabe Review completed. Closing this issue, thanks!
