### ISSUE TITLE
UAT Fix: Organizations with no datasets (Organizations page)

### ISSUE THREAD

**Issue by extinah** [CA-Data/Open-Data-Portal#123]
Right now, when a department has zero (0) datasets, it still displays.

Fix: Do not display departments that have zero datasets on the Organizations page. 

https://lab.data.ca.gov/organizations

Example: 
![b91fe5a5-7cc6-4e02-bf6e-7b1f17af07c3](https://user-images.githubusercontent.com/33840424/180331913-29fa6d72-2698-440d-83ba-b4104ccdab51.jpg)
![c03cf1c0-4b80-41a7-9e79-1ac81c5edd69](https://user-images.githubusercontent.com/33840424/180331919-0af47280-d3db-4d80-9ac2-cb75b28ea544.jpg)

**Comment by Greg-Watanabe** [comment]
@sharon-rabang 
This is done
https://sandbox.data.ca.gov/organizations

**Comment by sharon-rabang** [comment]
@Greg-Watanabe Thanks! Please add to https://lab.data.ca.gov/organizations and let me know when it's ready for review.

**Comment by sharon-rabang** [comment]
@Greg-Watanabe Review completed. This item still displays a zero (0):
![image](https://user-images.githubusercontent.com/99768807/188197859-0fa1c19e-a988-48ed-a090-cc09fa1063b1.png)

Please fix and let me know when it's ready for review. Thanks!

**Comment by Greg-Watanabe** [comment]
@sharon-rabang 
Original code fix was overwritten. I fixed again, here it is
https://sandbox.data.ca.gov/organizations

**Comment by sharon-rabang** [comment]
@Greg-Watanabe Great, thanks! Please add to https://lab.data.ca.gov and let me know when it's ready for review.

**Comment by sharon-rabang** [comment]
@Greg-Watanabe FYI - @hamiltonryan can review the changes in https://lab.data.ca.gov/ while I'm OOO. 

Please tag Ryan so he can let you know if there's a concern, or if this issue is complete and closed. 
Ryan, please also go to the [ODP Project Board](https://github.com/orgs/CA-Data/projects/1 ) and move this issue's card to "Done - In Production". Thanks!

**Comment by sharon-rabang** [comment]
@Greg-Watanabe @hamiltonryan Review completed. Closing this issue, thanks!
