### ISSUE TITLE
UAT fix: Link icon (external links)

### ISSUE THREAD

**Issue by extinah** [CA-Data/Open-Data-Portal#126]
Update code so all external links have a link icon.

![image](https://user-images.githubusercontent.com/33840424/180333539-d67a79ea-d58b-468d-9ac4-77d267c66ca5.png)

https://designsystem.webstandards.ca.gov/components/link-icon/readme/

**Comment by Greg-Watanabe** [comment]
@sharon-rabang 
This is done
https://sandbox.data.ca.gov/dataset?name=california-wic-authorized-product-list
https://sandbox.data.ca.gov/dataset?name=nifc-2022-wildfire-perimeters1

**Comment by sharon-rabang** [comment]
@Greg-Watanabe Thanks! I took a look and discovered that the API modal's "Usage documentation" doesn't display the external link icon. Please add the code to the modal as well.
![image](https://user-images.githubusercontent.com/99768807/181856089-68890397-8eb7-488e-bb47-389077b816ff.png)

@extinah Are these Download links considered external? Please let us know if they should be displaying external link icons:
![image](https://user-images.githubusercontent.com/99768807/181857246-54fe5a7c-09a2-44bf-a131-d8ef0146cbb2.png)

**Comment by Greg-Watanabe** [comment]
@sharon-rabang 
This is fixed:
https://sandbox.data.ca.gov/dataset?name=nifc-2022-wildfire-perimeters1

**Comment by sharon-rabang** [comment]
@Greg-Watanabe Thanks for including the modal. 
@extinah Please let us know if you have any concerns with the external link icon being part of the Download links. If there are no concerns, we will move forward with adding the icons to [lab.data.ca.gov](https://lab.data.ca.gov/).

**Comment by extinah** [comment]
@Greg-Watanabe  @sharon-rabang  I think any download links that are from the data portal should NOT have the external link icon. If we can someone include those domains as "internal" that'd be best. otherwise it's confusing why the downloads would happen outside the portal.

**Comment by Greg-Watanabe** [comment]
Do you want me to exclude all "download" links, or certain domains or ? 
Please specify.

**Comment by sharon-rabang** [comment]
@Greg-Watanabe @extinah Please exclude all "Download" links and "Download file" links. Here's a "Download file" link example"
![image](https://user-images.githubusercontent.com/99768807/182447897-47aa4d70-75d0-4ae5-9452-5df1bbd6833b.png)

If these two download link types are the only ones that go to the same domain, then you can exclude that domain. Please let us know which approach works out best. Thanks!

**Comment by Greg-Watanabe** [comment]
@sharon-rabang 
I've removed the icon from all "Download" links and "Download file" links.
https://sandbox.data.ca.gov/dataset?name=nifc-2022-wildfire-perimeters1

**Comment by sharon-rabang** [comment]
@Greg-Watanabe Looks good, thanks! Please add the change to https://lab.data.ca.gov/ and let me know when it's done.

**Comment by sharon-rabang** [comment]
@Greg-Watanabe Review completed. The regular pages display the external link icons correctly. However, it is still missing from the API:
![image](https://user-images.githubusercontent.com/99768807/188200578-67705035-a969-4ca6-aa7d-c77806ea417a.png)

Please fix and let me know when it's ready for review, thanks!

**Comment by Greg-Watanabe** [comment]
@sharon-rabang 
This is done
https://sandbox.data.ca.gov/dataset/covid-19-wastewater-surveillance-data-california

**Comment by sharon-rabang** [comment]
@Greg-Watanabe Great, thanks! Please add to https://lab.data.ca.gov/ and let me know when it's ready for review.

**Comment by sharon-rabang** [comment]
@Greg-Watanabe @hamiltonryan Review completed. Closing this issue, thanks!
