### ISSUE TITLE
UAT Fix: Sitemap link correction (all datasets link)

### ISSUE THREAD

**Issue by extinah** [CA-Data/Open-Data-Portal#127]
Update all datasets link in the sitemap. https://lab.data.ca.gov/sitemap

Current: https://lab.data.ca.gov/datasets
Corrected link: https://lab.data.ca.gov/datasets?q=

**Comment by Greg-Watanabe** [comment]
@sharon-rabang 
This is fixed
https://sandbox.data.ca.gov/sitemap

**Comment by sharon-rabang** [comment]
@Greg-Watanabe Looks good, thanks! Please add the change to https://lab.data.ca.gov/ and let me know when it's done.

**Comment by sharon-rabang** [comment]
@Greg-Watanabe Review completed. Closing this issue, thanks!
