### ISSUE TITLE
PRIORITY 1: Underlying code changes

### ISSUE THREAD

**Issue by extinah** [CA-Data/Open-Data-Portal#129]
**LAUNCH PRIORITY 1**
Please have these items completed before moving on to UAT fixes. 
Refer to Jason for more details. 

Make code more organized/efficient.

At least discuss before go live. Not a showstopper.

**Comment by sharon-rabang** [comment]
@timothyshambra Please work on this one, since you're familiar with it. You can work with @jon-grant-state-ca-gov if you need support. Thanks!

**Comment by yesenia-gtz** [comment]
**PRIORITY 1:**
@timothyshambra @jon-grant-state-ca-gov
Please refer to the [attached document outlining code cleanup](https://docs.google.com/document/d/1lEumS-W_w9S4YbTN75HmFXZYygqWe1JdFpJnQvxiBM8/edit) needs

Areas of focus:
**Jon:** Search/Filters code clean up
**Tim:** Layout /body code clean up

**Comment by sharon-rabang** [comment]
@timothyshambra @jon-grant-state-ca-gov Please include this simple change for consistency, when you work on the Topic cards on the [homepage](https://lab.data.ca.gov/) and [Topics](https://lab.data.ca.gov/topics) landing page.

Change "Datasets" to "datasets" for sentence-case consistency:
![image](https://user-images.githubusercontent.com/99768807/181308392-1e0e4639-0476-4fe7-9f75-09d7deb994a3.png)

**Comment by sharon-rabang** [comment]
@Greg-Watanabe Thanks for the confirming this has been completed. 
The request to change "Datasets" to "datasets" for sentence-case consistency will continue to be in the [Q3 design fixes](https://coda.io/d/NextGen-Open-Data-Portal_df6Kb2geJxZ/Q3-design-fixes_suR8z#_lubE7) list.

Closing this issue, thanks!
