### ISSUE TITLE
Design Fix: Add ODP Favicon

### ISSUE THREAD

**Issue by sharon-rabang** [CA-Data/Open-Data-Portal#130]
Files ready for dev: [favicon](https://teams.microsoft.com/_#/files/General?groupId=7c821265-5c5d-47a8-bbdc-86598101af7d&threadId=19%3A2tsxZUIe5bE5lFzYcggnwphmEqpuhBGFJMdmM9bV3v81%40thread.tacv2&ctx=channel&context=favicon&rootfolder=%252Fsites%252FOpenDataPortal%252FShared%2520Documents%252FGeneral%252FDesign%2520Assets%252Ffavicon)

- Generated in [FavIcon.pro](http://www.favicon.pro/)
- Validated in [Favicon Checker](http://www.colinkeany.com/favicon-checker/)

**Comment by sharon-rabang** [comment]
@timothyshambra Please work on this one, thanks!

**Comment by sharon-rabang** [comment]
Reassigning to @Greg-Watanabe. Please reach out to Tim about the work he had in progress.

**Comment by Greg-Watanabe** [comment]
@sharon-rabang 
This was done on sandbox https://sandbox.data.ca.gov/

**Comment by sharon-rabang** [comment]
@Greg-Watanabe Looks good, thanks! Please add the change to https://lab.data.ca.gov/ and let me know when it's done.

**Comment by sharon-rabang** [comment]
@Greg-Watanabe Review completed. Closing this issue, thanks!
