### ISSUE TITLE
Design Fix: Add missing topic icon and topic name under "About this dataset"

### ISSUE THREAD

**Issue by sharon-rabang** [CA-Data/Open-Data-Portal#131]
Add missing info on [DGS-Approved Non-Competitive Bids](https://sandbox.data.ca.gov/dataset?name=dgs-approved-non-competitive-bids) and any other instances.

**Comment by sharon-rabang** [comment]
@timothyshambra Please work on this one, thanks!

**Comment by sharon-rabang** [comment]
Guidelines:
- For missing topic label: Use the ODP favicon and “General” as text.
- For multiple topic labels: Use the ODP favicon and list of topics as text.
![image](https://user-images.githubusercontent.com/99768807/181306111-8b2e9a82-04fb-4154-817d-7777fb29c2c7.png)

**Comment by Greg-Watanabe** [comment]
@sharon-rabang 
This is complete
https://sandbox.data.ca.gov/dataset/hazardous-waste-id-numbers
https://sandbox.data.ca.gov/dataset/covid-19-staff-data

**Comment by sharon-rabang** [comment]
@Greg-Watanabe Looks good, thanks! Please add the change to https://lab.data.ca.gov/ and let me know when it's done.

**Comment by sharon-rabang** [comment]
@Greg-Watanabe Review completed. Closing this issue, thanks!
