### ISSUE TITLE
UAT Fix: Cursor issue on Org. Search page

### ISSUE THREAD

**Issue by sharon-rabang** [CA-Data/Open-Data-Portal#135]
The cursor on the Organization Search page displays the Text cursor instead of the hand cursor when hovering over a link.
[Cal Fire](https://lab.data.ca.gov/organization/datasets?q=&publisher=cal-fire)

**Comment by sharon-rabang** [comment]
@timothyshambra Please work on this one, thanks!

**Comment by Greg-Watanabe** [comment]
@sharon-rabang 
This was fixed on sandbox
https://sandbox.data.ca.gov/organization/datasets?q=&publisher=cal-fire

**Comment by sharon-rabang** [comment]
@Greg-Watanabe Looks good, thanks! Please add the change to https://lab.data.ca.gov/ and let me know when it's done.

**Comment by sharon-rabang** [comment]
@Greg-Watanabe Review completed. Closing this issue, thanks!
