### ISSUE TITLE
Design Fix: Search bar focus states

### ISSUE THREAD

**Issue by sharon-rabang** [CA-Data/Open-Data-Portal#138]
Fix search bar focus states for usability:

- [Homepage](https://lab.data.ca.gov/), search bar: Extend the focus state’s yellow border to include the icon’s container on the left. 
- [Search page](https://lab.data.ca.gov/datasets?q=COVID-19+Wastewater+Surveillance+Data.+California), search bar: Extend the focus state’s yellow border to include the icon’s container on the right. 
- [All datasets](https://lab.data.ca.gov/datasets?q=), search bar: Extend the focus state’s yellow border to include the icon’s container on the right. 
- [Topic page](https://lab.data.ca.gov/topic/datasets?q=&topic=covid-19), search bar: Extend the focus state’s yellow border to include the icon’s container on the right. 
- [Organization page](https://lab.data.ca.gov/organization/datasets?q=&publisher=cal-fire), search bar: Extend the focus state’s yellow border to include the icon’s container on the right.

**Comment by Greg-Watanabe** [comment]
@sharon-rabang 
I don't think this is possible, since the submit button and text field are highlighted separately when the user tabs to them. There might be an accessibility issue if we change this behavior.

**Comment by Greg-Watanabe** [comment]
@sharon-rabang 
This is done
https://sandbox.data.ca.gov/
https://sandbox.data.ca.gov/datasets?q=

**Comment by sharon-rabang** [comment]
@Greg-Watanabe Review completed. Closing this issue, thanks!
