### ISSUE TITLE
Search Filters Bug

### ISSUE THREAD

**Issue by hamiltonryan** [CA-Data/Open-Data-Portal#146]
When searching in the All Data sets page, if multiple tag filters are applied the results will should a number for datasets, but not show any of the actual datasets.
![Filter Tag Bug](https://user-images.githubusercontent.com/101579462/183461454-834697a8-1b18-41fb-a09e-7d9ce6e9615b.PNG)

**Comment by Greg-Watanabe** [comment]
This appears to have been fixed
https://sandbox.data.ca.gov/datasets?q=&topic=natural-resources&page=0&tag=natural+resources%2Cenvironment
https://lab.data.ca.gov/datasets?q=&topic=natural-resources&page=0&tag=natural+resources%2Cenvironment
