### ISSUE TITLE
404 page design -  A-PS-006_404page

### ISSUE THREAD

**Issue by extinah** [CA-Data/Open-Data-Portal#24]
Identified that a 404 page needed to be designed during QA.

**Comment by extinah** [comment]
@KarunaTamatam  @yesenia-gtz 
Recommend to complete early in Q2 as a high priority.

**Comment by sharon-rabang** [comment]
Updated Design System UI Kit [404 Template](https://www.figma.com/file/veQuKQHf8gK5JdFEoMLGRD/UI-Design-kit?node-id=5%3A3009) with approved content.

**Comment by yesenia-gtz** [comment]
Done
