### ISSUE TITLE
Data preview page - Type styles

### ISSUE THREAD

**Issue by sharon-rabang** [CA-Data/Open-Data-Portal#36]
Fix the type styles on this page for consistency:

1. Data preview, heading: Change from thin text to **bold** text.
2. Add data details and style the same way they display on the Search results page. Lead with bold text and follow with regular text:
**Published by:** State Water Resources Control Board
**File details:** CSV, 58.16 MB
**Access data:** [Download file](https://test-nextgenportal.azurewebsites.net/Download) | [API](https://test-nextgenportal.azurewebsites.net/api)
3. (Add space between "Access data" and the table)
4. Table pagination, 1-5 of 99 <   >: Change from right-aligned to left-aligned.

**Comment by yesenia-gtz** [comment]
Pending style fixes, delayed by server issue
