### ISSUE TITLE
Synthesize insights from the intercept 

### ISSUE THREAD

**Issue by yesenia-gtz** [CA-Data/Open-Data-Portal#4]
Synthesize insights from the intercept

**Comment by KarunaTamatam** [comment]
Sorry, Yesenia. Looks like I accidentally closed it.

**Comment by KarunaTamatam** [comment]
Thank You.

**Comment by hamiltonryan** [comment]
Checking to make sure the intercept is up, for further update. If the intercept is up, it will usually take at least a week or two to get enough feedback to report anything out.

**Comment by yesenia-gtz** [comment]
@byronsays @jasonlally 

Below is the Ethnio intercept for the current CA Open Data Portal. This is a trimmed down intercept and we can modify questions/ functionality as needed.

Javascript for web intercept:


<script type="text/javascript" language="javascript" src="//ethn.io/88644.js" async="true" charset="utf-8"></script>

**Comment by jasonlally** [comment]
Just sent off information to the vendor to get extensions for google tag manager installed. Once we have that in place, we'll test dropping in the ethn.io intercept in our open data sandbox environment before pushing to the live site.
